# Dependencies
# markdown:         redcarpet
highlighter:     rouge

# Permalinks
permalink:        pretty

# Setup
title:            Changli Website
#tagline:          
description:      'Atomsbase Basic.'
url:              http://changli6.github.io
baseurl:     ''

author:
  name:           'Changli Liu'
  url:            https://twitter.com

plugins:  [jekyll-paginate]

paginate:         5

# Custom vars
#version:          2.1.0

github:
  repo:           https://github.com/changli6
