# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Changli Website
tagline:          'A Jekyll theme'
description:      'A brazen two-column.'
url:              http://changli6.github.io
baseurl:          /

author:
  name:           'Changli Liu'
  url:            https://twitter.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/changli6
